### ISSUE TITLE
Allow role conversion

### ISSUE THREAD

**Issue by hschreck** [128keaton/Heat#8]

**Comment by 128keaton** [comment]
More clarification requested @hschreck

**Comment by hschreck** [comment]
For the upcoming project, we'll be checking in all units as "Role A", because Roles A and B are all the same specs.  Can we build into the unboxing process the ability to assign the first X units to role B?

**Comment by hschreck** [comment]
Role conversion should happen during the unboxing stage.  All units will be received in as "Role A" for this upcoming project, but we will need to assign a certain number during unboxing as "Role B".

Basically, a way to re-assign roles during unboxing will likely be necessary.
